use project;
-- ALTER TABLE customer ADD CONSTRAINT FOREIGN KEY(Sales_ID) REFERENCES sales(Sales_ID);
-- ALTER TABLE manager ADD CONSTRAINT FOREIGN KEY(Payment_ID) REFERENCES payment(Payment_ID);
-- ALTER TABLE manager ADD CONSTRAINT FOREIGN KEY(Product_ID) REFERENCES product(Product_ID);
-- ALTER TABLE sales ADD CONSTRAINT FOREIGN KEY(Employee_ID) REFERENCES employee(Employee_ID);
-- ALTER TABLE sales ADD CONSTRAINT FOREIGN KEY(Product_ID) REFERENCES product(Product_ID);
-- ALTER TABLE manage ADD CONSTRAINT FOREIGN KEY(Sales_ID) REFERENCES sales(Sales_ID);
-- ALTER TABLE manage ADD CONSTRAINT FOREIGN KEY(Product_ID) REFERENCES product(Product_ID);